### ISSUE TITLE
Unit test inverted_mask()

### ISSUE THREAD

**Issue by SarahS16** [libembeddedhal/libxbitset#8]

**Comment by kammce** [comment]
@SarahS16 and I spoke about this on Discord. This particular feature does not exists and I'm not personally sure why I requested @SarahS16 create the issue and what the original feature was supposed to be. We assume I meant some new feature where you can make the inverted version of bitrange mask, or maybe a means to generate two masks from a bitrange mask that is the regions outside of the bitrange. 

Either way there is not current need for this feature so this issue will be closed.
